spring:
  profiles:
    active: pro

---
spring:
  config:
    activate:
      on-profile: dev
server:
  port: 81
---
spring:
  config:
    activate:
      on-profile: test
server:
  port: 82
---
spring:
  config:
    activate:
      on-profile: pro

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/mydatabase
    username: root
    password: M19790929
  servlet:
    multipart:
          max-file-size: -1    # 不限制单个文件
          max-request-size: -1 # 不限制整个请求
file:
  teacher-dir: src/main/java/com/ccut/teachingaisystem/download/file/teacher/
  image_dir: src/main/java/com/ccut/teachingaisystem/download/file/usersImage/
  log-dir: src/main/java/com/ccut/teachingaisystem/download/file/log/
  questionImg-dir: src/main/java/com/ccut/teachingaisystem/download/file/questionImg/
  defaultImg-dir: src/main/resources/static/userImgs/f1c90710-3adc-47fb-a7c7-4e2b3b898fe2v2-f37c17fa026dfbb46df18af78ef09b1d_r.jpg
myAi:
  service:
    ip: 100.125.72.218
    port: :8000
server:
  port: 83

mybatis:
  type-handlers-package: com.ccut.teachingaisystem.config
